<?php declare(strict_types=1);

namespace HDSSolutions\Bancard\Models\X;

use HDSSolutions\Bancard\Models\Base\Model;

/**
 * @property-read int $id Resource Identifier
 * @property string $type Payment type, see {@see PaymentType}
 * @property int $shop_process_id Unique identifier of Shop Process
 * @property float $amount Amount of the Payment
 * @property string $description Description of the Payment
 * @property string $currency Currency of Payment, see {@see Currency}
 * @property ?int $card_id Card Identifier of the Payment
 * @property-read string $status Current status of the Payment, see {@see PaymentStatus}
 * @property-read ?string $process_id Process Identifier generated by Bancard
 * @property-read ?string $process_result Result of the payment process
 * @property-read ?string $rollback_result Result of the rollback process
 */
abstract class Payment extends Model implements Contracts\Payment {

    protected $fillable = [
        'type',
        'shop_process_id',
        'amount',
        'description',
        'currency',
        'card_id',
    ];

}
